
  CREATE TABLE "CAP_GRUP_DIA" 
   (	"GRD_CLAVE" NUMBER NOT NULL ENABLE, 
	"GRD_ITEM" NUMBER, 
	"GRD_FECHA" DATE, 
	 CONSTRAINT "PKGRD" PRIMARY KEY ("GRD_CLAVE", "GRD_FECHA")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CAP_GRUP_DIA" ADD CONSTRAINT "FKGRD" FOREIGN KEY ("GRD_CLAVE")
	  REFERENCES "CAP_GRUPO_GUARDIA" ("GRU_CLAVE") ENABLE;

   COMMENT ON COLUMN "CAP_GRUP_DIA"."GRD_FECHA" IS 'fecha a la que le toca a la guardia';