
  CREATE TABLE "CAP_GRUPO_GUARDIA" 
   (	"GRU_CLAVE" NUMBER NOT NULL ENABLE, 
	"GRU_JEFE" NUMBER, 
	"GRU_ESTADO" VARCHAR2(1), 
	"GRU_FEC_INI" DATE, 
	"GRU_FEC_GRAB" DATE DEFAULT SYSDATE, 
	"GRU_NRO_GUARDIA" NUMBER, 
	"GRU_OBSERVACION" VARCHAR2(250), 
	"GRU_PERIODO" NUMBER, 
	 CONSTRAINT "PKG_GRUPO" PRIMARY KEY ("GRU_CLAVE")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CAP_GRUPO_GUARDIA" ADD CONSTRAINT "FK_PERIODO_GRUPO" FOREIGN KEY ("GRU_PERIODO")
	  REFERENCES "CAP_PERIODO_GUARDIA" ("PERG_CLAVE") ENABLE;

   COMMENT ON COLUMN "CAP_GRUPO_GUARDIA"."GRU_PERIODO" IS 'codigo de periodo en el cual pernetece el grupo ';

  CREATE OR REPLACE EDITIONABLE TRIGGER "CAP_GRU_GUARDIA_BE_I" 
  before insert
  on CAP_GRUPO_GUARDIA 
  for each row
declare
  -- local variables here
begin
  IF :NEW.GRU_CLAVE IS NULL THEN
    SELECT SEQ_GRUPO.NEXTVAL INTO :NEW.GRU_CLAVE FROM DUAL;
  
  END IF;
  :new.gru_fec_grab:=sysdate;
end CAP_GRU_GUARDIA_BE_I;

/
ALTER TRIGGER "CAP_GRU_GUARDIA_BE_I" ENABLE;