
  CREATE TABLE "CAP_PERSONAS" 
   (	"PER_CLAVE" NUMBER NOT NULL ENABLE, 
	"PER_NOMBRE" VARCHAR2(100), 
	"PER_APELLIDO" VARCHAR2(100), 
	"PER_CI" NUMBER, 
	"PER_CELULAR" VARCHAR2(20), 
	"PER_DIRECCION" VARCHAR2(200), 
	"PER_ESTADO_CIVIL" VARCHAR2(1), 
	"PER_FECHA_NAC" DATE, 
	"PER_FECHA_INGRESO" DATE DEFAULT SYSDATE, 
	"PER_RANGO" NUMBER, 
	"PER_TIPO_V" NUMBER, 
	"PER_ESTADO" VARCHAR2(1), 
	"PER_IDENTIDAD" NUMBER, 
	"PER_IND_USUARIO" VARCHAR2(1) DEFAULT 'S', 
	 CONSTRAINT "XPK_PERSONAS" PRIMARY KEY ("PER_CLAVE")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CAP_PERSONAS" ADD CONSTRAINT "FK_RANGO_PERSONA" FOREIGN KEY ("PER_RANGO")
	  REFERENCES "CAP_RANGO" ("RAN_CLAVE") ENABLE;
  ALTER TABLE "CAP_PERSONAS" ADD CONSTRAINT "FK_TIPO_PERSONA" FOREIGN KEY ("PER_TIPO_V")
	  REFERENCES "CAP_TIPO_PERSONA" ("VOL_TCLAVE") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "CAP_PERSONA_BE_I" 
  before insert
  on CAP_PERSONAS
  for each row
declare
  -- local variables here
begin
  IF :NEW.per_clave IS NULL THEN
    SELECT seq_cap_persona.NEXTVAL INTO :NEW.per_clave FROM DUAL;
  END IF;
end CAP_persona_BE_I;

/
ALTER TRIGGER "CAP_PERSONA_BE_I" ENABLE;