
  CREATE TABLE "CAP_ASISTENCIA_GUARDIA" 
   (	"ASIS_CLAVE" NUMBER NOT NULL ENABLE, 
	"ASIS_GUARDIA" NUMBER, 
	"ASIS_FECHA" DATE, 
	"ASIS_VOLUNTARIO" NUMBER, 
	"ASIS_ASISTENCIA" VARCHAR2(1), 
	"ASIS_TIPO" VARCHAR2(1), 
	"ASIS_OBS" VARCHAR2(250), 
	 CONSTRAINT "CAP_ASISTENCIA_GUARDIA_PK" PRIMARY KEY ("ASIS_CLAVE")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BI_CAP_ASISTENCIA_GUARDIA" 
  before insert on "CAP_ASISTENCIA_GUARDIA"               
  for each row  
begin   
  if :NEW."ASIS_CLAVE" is null then 
    select "CAP_ASISTENCIA_GUARDIA_SEQ".nextval into :NEW."ASIS_CLAVE" from sys.dual; 
  end if; 
end;

/
ALTER TRIGGER "BI_CAP_ASISTENCIA_GUARDIA" ENABLE;