
  CREATE TABLE "CAP_PERIODO_DIAS" 
   (	"DIA_CLAVE" NUMBER NOT NULL ENABLE, 
	"DIA_NOMBRE" NUMBER NOT NULL ENABLE, 
	"DIA_HORA_ENTRADA" DATE DEFAULT to_DATE('01/01/2018 07:00:00','DD/MM/YYYY HH24:MI:SS'), 
	"DIA_HORA_SALIDA" DATE DEFAULT to_DATE('01/01/2018 07:00:00','DD/MM/YYYY HH24:MI:SS'), 
	 CONSTRAINT "XPK_PERI_DIA" PRIMARY KEY ("DIA_CLAVE", "DIA_NOMBRE")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CAP_PERIODO_DIAS" ADD CONSTRAINT "FKS_PERI_DIA" FOREIGN KEY ("DIA_CLAVE")
	  REFERENCES "CAP_PERIODO_GUARDIA" ("PERG_CLAVE") ON DELETE CASCADE ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TR_BE_IU_DIAS_PERIODO" 
  before insert or update
  on CAP_PERIODO_DIAS 
  for each row
--declare
  -- local variables here
begin
  null;
end tr_be_iu_dias_periodo;

/
ALTER TRIGGER "TR_BE_IU_DIAS_PERIODO" ENABLE;