
  CREATE TABLE "CAP_TIPO_PERSONA" 
   (	"VOL_TCLAVE" NUMBER NOT NULL ENABLE, 
	"VOL_T_DESCRIPCION" VARCHAR2(250), 
	"VOL_T_NOMBRE" VARCHAR2(100), 
	 CONSTRAINT "XPK_T_PERSONA" PRIMARY KEY ("VOL_TCLAVE")
  USING INDEX  ENABLE
   ) ;

   COMMENT ON COLUMN "CAP_TIPO_PERSONA"."VOL_TCLAVE" IS 'clave del tipo de documento ';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TR_T_PERSONA" 
  before insert
  on CAP_TIPO_PERSONA 
  for each row
declare
  V_CLAVE NUMBER:=0;
begin
  IF INSERTING THEN
    SELECT NVL(MAX(P.VOL_TCLAVE),0)+1 INTO V_CLAVE FROM CAP_TIPO_PERSONA P;
    :NEW.VOL_TCLAVE:=V_CLAVE;
  END IF;
end TR_T_PERSONA;

/
ALTER TRIGGER "TR_T_PERSONA" ENABLE;