
  CREATE TABLE "CAP_CALIFIC_DET" 
   (	"CALD_CLAVE" NUMBER NOT NULL ENABLE, 
	"CALD_ITEM" NUMBER NOT NULL ENABLE, 
	"CALD_CRIT" NUMBER, 
	"CALD_PUNTAJE" NUMBER, 
	"CALD_OBSERVACION" VARCHAR2(250), 
	 CONSTRAINT "PK_CALD_CLAVE" PRIMARY KEY ("CALD_CLAVE", "CALD_ITEM")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CAP_CALIFIC_DET" ADD CONSTRAINT "FK_CALD_ENCAB" FOREIGN KEY ("CALD_CLAVE")
	  REFERENCES "CAP_CALIFICACION" ("CAL_CLAVE") ENABLE;