
  CREATE TABLE "CAP_PERIODO_GUARDIA" 
   (	"PERG_CLAVE" NUMBER NOT NULL ENABLE, 
	"PERG_FEC_INI" DATE NOT NULL ENABLE, 
	"PERG_FEC_FIN" DATE NOT NULL ENABLE, 
	"PERG_CAN_GUARD" NUMBER, 
	 CONSTRAINT "CAP_PERIODO_GUARDIA_PK" PRIMARY KEY ("PERG_CLAVE")
  USING INDEX  ENABLE
   ) ;

   COMMENT ON COLUMN "CAP_PERIODO_GUARDIA"."PERG_CAN_GUARD" IS 'CANTIDAD DE GUARDIAS POR SEMANA';

  CREATE OR REPLACE EDITIONABLE TRIGGER "BI_CAP_PERIODO_GUARDIA" 
  before insert on "CAP_PERIODO_GUARDIA"               
  for each row  
begin   
  if :NEW."PERG_CLAVE" is null then 
    select "CAP_PERIODO_GUARDIA_SEQ".nextval into :NEW."PERG_CLAVE" from sys.dual; 
  end if; 
end;

/
ALTER TRIGGER "BI_CAP_PERIODO_GUARDIA" ENABLE;