
  CREATE TABLE "CAP_RANGO" 
   (	"RAN_CLAVE" NUMBER NOT NULL ENABLE, 
	"RAN_DESCRIPCION" VARCHAR2(250), 
	"RAN_POSICION" NUMBER, 
	"RAN_RANGO" VARCHAR2(100), 
	 CONSTRAINT "XPK_RANGO" PRIMARY KEY ("RAN_CLAVE")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TR_RANGO" 
  before insert
  on CAP_RANGO 
  for each row
declare
  V_CLAVE NUMBER:=0;
begin
  IF INSERTING THEN
    SELECT NVL(MAX(R.RAN_CLAVE),0)+1 INTO V_CLAVE FROM CAP_RANGO R;
    :NEW.RAN_CLAVE:=V_CLAVE;
  END IF;
end TR_RANGO;

/
ALTER TRIGGER "TR_RANGO" ENABLE;