
  CREATE TABLE "CAP_MARCACION" 
   (	"MAR_CLAVE" NUMBER NOT NULL ENABLE, 
	"MAR_PERSONA" NUMBER NOT NULL ENABLE, 
	"MAR_HORA_MAR" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT null NOT NULL ENABLE, 
	"MAR_TIPO" VARCHAR2(1), 
	"CAP_HORA" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "CAP_MARCACION_PK" PRIMARY KEY ("MAR_CLAVE")
  USING INDEX  ENABLE
   ) ;