create or replace PACKAGE CH003_MARCACION IS
  -- AUTHOR  : PRO1
  -- CREATED : 21/10/2020 8:22:55
  -- PURPOSE :
  -- PUBLIC TYPE DECLARATIONS
  PROCEDURE PP_INSERTAR_MARCACION(I_CLAVE IN NUMBER, I_TIPO IN VARCHAR2);
  PROCEDURE PP_CONSULTAR_VOLUNTARIO(I_CI     IN NUMBER,
                                    I_NOMBRE OUT VARCHAR2,
                                    O_TIPO   OUT VARCHAR2);
  PROCEDURE PP_CERRAR_MARCACION;
END CH003_MARCACION;
/