
  CREATE TABLE "DOCUMENTOS_STK_DET" 
   (	"DOCD_CLAVE" NUMBER NOT NULL ENABLE, 
	"DOCD_ARTICULO" NUMBER NOT NULL ENABLE, 
	"DOCD_CANTIDAD" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PKS_DOCUMENTO_DET" PRIMARY KEY ("DOCD_CLAVE", "DOCD_ARTICULO")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "DOCUMENTOS_STK_DET" ADD CONSTRAINT "FKS_ARTICULO_DOCUMENTO" FOREIGN KEY ("DOCD_ARTICULO")
	  REFERENCES "STK_ARTICULO" ("ART_CLAVE") ENABLE;
  ALTER TABLE "DOCUMENTOS_STK_DET" ADD CONSTRAINT "FKS_DOCUMENTO_DET" FOREIGN KEY ("DOCD_CLAVE")
	  REFERENCES "DOCUMENTOS_STK" ("DOCS_CLAVE") ENABLE;