create or replace FUNCTION GEN_DEVUELVE_USER RETURN VARCHAR2 IS
  V_LOGIN VARCHAR2(100);
BEGIN
  IF USER = 'APEX_PUBLIC_USER' THEN
    V_LOGIN := SUBSTR(SYS_CONTEXT('USERENV', 'CLIENT_INFO'),
                      INSTR(SYS_CONTEXT('USERENV', 'CLIENT_INFO'), ':') + 1);
  ELSIF USER = 'ANONYMOUS' THEN
    V_LOGIN := 'ADCS';
  ELSE
    V_LOGIN := USER;
  END IF;
/*
  IF V('APP_USER') IS NULL THEN
    V_LOGIN := USER;
  ELSE
    V_LOGIN := V('APP_USER');
  END IF;*/
  RETURN V_LOGIN;
END;
/