
  CREATE TABLE "MENU" 
   (	"MEN_CLAVE" NUMBER, 
	"MEN_NOMBRE" VARCHAR2(250), 
	"MEN_ICONO" VARCHAR2(50), 
	"MEN_IMAGEN" VARCHAR2(50), 
	"MEN_ATTRR_VALUE" VARCHAR2(50), 
	"MEN_NIVEL" NUMBER, 
	"MEN_TARGET" NUMBER, 
	"MEN_TIPO" NUMBER
   ) ;

  ALTER TABLE "MENU" ADD CONSTRAINT "FK_TIPO_MENU" FOREIGN KEY ("MEN_TIPO")
	  REFERENCES "TIPO_MENU" ("CLAVE_TIPO_MENU") ENABLE;