
  CREATE TABLE "STK_MOVILES" 
   (	"MOV_CLAVE" NUMBER NOT NULL ENABLE, 
	"MOV_NOMBRE" VARCHAR2(150) NOT NULL ENABLE, 
	"MOV_ABREV" VARCHAR2(20) NOT NULL ENABLE, 
	"MOV_MARCA" VARCHAR2(50) NOT NULL ENABLE, 
	"MOV_CHAPA" VARCHAR2(50) NOT NULL ENABLE, 
	"MOV_ANHO_FAB" VARCHAR2(5) NOT NULL ENABLE, 
	"MOV_ESTADO" NUMBER NOT NULL ENABLE, 
	"MOV_FECH_ADQUISICION" DATE, 
	 CONSTRAINT "STK_MOVILES_PK" PRIMARY KEY ("MOV_CLAVE")
  USING INDEX  ENABLE
   ) ;

   COMMENT ON COLUMN "STK_MOVILES"."MOV_FECH_ADQUISICION" IS 'fecha en la institucion adquirio el movil';

  CREATE OR REPLACE EDITIONABLE TRIGGER "BI_STK_MOVILES" 
  before insert on "STK_MOVILES"               
  for each row  
begin   
  if :NEW."MOV_CLAVE" is null then 
    select "STK_MOVILES_SEQ".nextval into :NEW."MOV_CLAVE" from sys.dual; 
  end if; 
end;

/
ALTER TRIGGER "BI_STK_MOVILES" ENABLE;