
  CREATE TABLE "STK_ARTICULO" 
   (	"ART_CLAVE" NUMBER NOT NULL ENABLE, 
	"ART_NOMBRE" VARCHAR2(250) NOT NULL ENABLE, 
	"ART_ABREVIATURA" VARCHAR2(50), 
	"ART_TIPO" NUMBER NOT NULL ENABLE, 
	"ART_ESTADO" VARCHAR2(1) NOT NULL ENABLE, 
	"ART_ORIGEN" VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT "STK_ARTICULO_PK" PRIMARY KEY ("ART_CLAVE")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BI_STK_ARTICULO" 
  before insert on "STK_ARTICULO"               
  for each row  
begin   
  if :NEW."ART_CLAVE" is null then 
    select "STK_ARTICULO_SEQ".nextval into :NEW."ART_CLAVE" from sys.dual; 
  end if; 
end;

/
ALTER TRIGGER "BI_STK_ARTICULO" ENABLE;