
  CREATE TABLE "STK_DEPOSITO_FISICO" 
   (	"DEP_CLAVE" NUMBER NOT NULL ENABLE, 
	"DEP_NOMBRE" VARCHAR2(50) NOT NULL ENABLE, 
	"DEP_DESCRIPCION" VARCHAR2(250), 
	 CONSTRAINT "STK_DEPOSITO_FISICO_PK" PRIMARY KEY ("DEP_CLAVE")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BI_STK_DEPOSITO_FISICO" 
  before insert on "STK_DEPOSITO_FISICO"               
  for each row  
begin   
  if :NEW."DEP_CLAVE" is null then 
    select "STK_DEPOSITO_FISICO_SEQ".nextval into :NEW."DEP_CLAVE" from sys.dual; 
  end if; 
end;

/
ALTER TRIGGER "BI_STK_DEPOSITO_FISICO" ENABLE;