
  CREATE TABLE "TIPO_MENU" 
   (	"CLAVE_TIPO_MENU" NUMBER NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(250), 
	"MEN_ATTRR_VALUE" VARCHAR2(250), 
	 CONSTRAINT "XPK_TIPO_MENU" PRIMARY KEY ("CLAVE_TIPO_MENU")
  USING INDEX  ENABLE
   ) ;